import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { fakeHabitDB, category } from "../lib/db";
import Header from "../components/Header";
import CreateNewForm from "../components/Form/AddForm";

import Card from "../components/Form/Cards";

export default function Home() {
  const [cardData, setCardData] = useState(fakeHabitDB);

  function appendCard(name) {
    setCardData((cardData) => [
      ...cardData,
      {
        name,
      },
    ]);
  }

  return (
    <div>
      <Header />
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <div>
          {cardData.map((card) => (
            <Card key={card.id} name={card.name} />
          ))}
        </div>
        <CreateNewForm onAddNewData={appendCard} />
      </Main>
    </div>
  );
}

const Main = styled.main`
  background-color: white;
`;
