import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { HabitsData, category } from "../lib/db";
import Header from "../components/Header";
import CreateNewForm from "../components/CreateNewForm";

import Card from "../components/Cards";
import { nanoid } from "nanoid";

export default function Home() {
  const [cardData, setCardData] = useState(HabitsData);

  function appendCard(name) {
    setCardData((cardData) => [
      ...cardData,
      {
        name,
        id: nanoid(),
      },
    ]);
  }
  function deleteCard(id) {
    const updatedHabitsList = cardData.filter((card) => card.id !== id);
    setCardData(updatedHabitsList);
  }
  return (
    <div>
      <Header />
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <div>
          {cardData.map((card) => {
            return (
              <Card
                key={card.id}
                name={card.name}
                onDelete={() => deleteCard(card.id)}
              />
            );
          })}
        </div>
        <CreateNewForm onAddNewData={appendCard} />
      </Main>
    </div>
  );
}

const Main = styled.main`
  background-color: white;
`;
