import Head from "next/head";
import { useEffect, useState } from "react";
import styled from "styled-components";
import { HabitsData, category } from "../lib/db";
import Header from "../components/Header";
import CreateNewForm from "../components/CreateNewForm";

import Card from "../components/Card";
import { nanoid } from "nanoid";
import Navigation from "../components/Navigation";

export default function Home() {
  const [cardData, setCardData] = useState(HabitsData);

  function appendCard(name) {
    setCardData((cardData) => [
      ...cardData,
      {
        name,
        id: nanoid(),
      },
    ]);
  }
  function deleteCard(id) {
    const updatedHabitsList = cardData.filter((card) => card.id !== id);
    setCardData(updatedHabitsList);
  }
  function toggleCard(id) {
    const updateToggleHabit = cardData.filter((card) => card.id !== id);
    const toggledHabit = cardData.find((card) => card.id === id);
    toggledHabit.checked = !toggledHabit.checked;
    updateToggleHabit.unshift(toggledHabit);
    setCardData(updateToggleHabit);
  }
  return (
    <>
      <Header />
      <Head>
        <title>My App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Main>
        <div>
          <Headline>Today</Headline>
          <HabitForTodayList>
            {cardData
              .filter((item) => !item.checked)
              .map((card, id) => {
                return (
                  <Card
                    id={id}
                    key={card.id}
                    name={card.name}
                    onDelete={() => deleteCard(card.id)}
                    onToggle={() => toggleCard(card.id)}
                  />
                );
              })}
          </HabitForTodayList>

          <Headline>Done</Headline>
          <HabitDone>
            {cardData
              .filter((item) => item.checked)
              .map((card, id) => {
                return (
                  <Card
                    id={id}
                    key={card.id}
                    name={card.name}
                    onDelete={() => deleteCard(card.id)}
                    onToggle={() => toggleCard(card.id)}
                  />
                );
              })}
          </HabitDone>
        </div>

        <CreateNewForm onAddNewData={appendCard} />

        <Navigation />
      </Main>
    </>
  );
}

const Main = styled.main`
  margin: 0;
`;

const Headline = styled.h2`
  color: black;
`;
const HabitForTodayList = styled.ul`
  font-size: 1.5em;
  color: pink;
`;

const HabitDone = styled.ul`
  font-size: 1.2em;
  filter: blur(0.04em);
`;
